myproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("ohq.urls")),
]

ohq/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'ohq'
urlpatterns = [
    path("", view=views.CourseListView.as_view(), name="index"),
    path("search", views.prepare_search, name="prepare_search"),
    path("search/q=<str:query>", views.search, name="search"),
    path("login_request", views.login_request, name="login_request"),
    path("logout", views.logout_request, name="logout"),
    path("login", views.login_request, name="login"),
    path("signup", views.signup_request, name="signup_request"),
    path("password", views.change_password, name="change_password"),
    path("change_preferred_name", views.change_preferred_name, name="change_preferred_name"),
    path("my_courses", views.MyCourseListView.as_view(), name="my_courses"),
    path("course/<int:pk>/change_status", views.change_queue_status, name="change_status"),
    path("course/<int:pk>/meeting_link", views.set_meeting_link, name="set_meeting_link"),
    path("course/<int:pk>", views.CourseQueueView.as_view(), name="course_queue"),
    path("course/<int:pk>/join_queue", views.join_queue, name="join_queue"),
    path("course/<int:pk>/quit_queue", views.quit_queue, name="quit_queue"),
    path("course/<int:pk>/invite_students", views.invite_students, name="invite_students"),
    path("course/<int:pk>/next_student", views.next_student, name="next_student"),
    path("course/<int:pk>/put_back", views.put_back, name="put_back"),
    path("course/<int:pk>/clear_queue", views.clear_queue, name="clear_queue"),
    path("course/<int:pk>/star_course", views.star_course, name="star_course"),
    path("course/<int:pk>/ajax", views.refresh_queue_view, name="refresh_queue_view"),

    ]

ohq/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.lookups import In

# Subject code
CPEN = "CPEN"
CPSC = "CPSC"
EECE = "EECE"
ELEC = "ELEC"
SUBJECT_CODE = [(CPEN, "CPEN"),
                (CPSC, "CPSC"),
                (EECE, "EECE"),
                (ELEC, "ELEC")]

# semester
W1 = "W1"
W2 = "W2"
S = "S"
SEMESTER = [(W1, "W1"),
            (W2, "W2"),
            (S, "S")]

def get_name_and_email_for_user(self):
    return self.first_name + " " + self.last_name + " (" + self.email + ")"
User.add_to_class("__str__", get_name_and_email_for_user)

class Course(models.Model):
    code = models.CharField(max_length=10)
    subject = models.CharField(null=False,
        max_length=5,
        choices=SUBJECT_CODE,
        default=CPEN)
    number = models.IntegerField(default=0)
    session = models.CharField(max_length=5, default="")
    semester = models.CharField(null=False,
        max_length=2,
        choices=SEMESTER,
        default=W1)
    course_name = models.CharField(max_length=100, default="")
    status = models.BooleanField(default=False)
    meeting_link = models.URLField(default="")
    teaching_instructor = models.ManyToManyField("Instructor")

    def __str__(self):
        if self.course_name:
            return self.code + ": " + self.course_name
        return self.code

# Student
class Student(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    preferred_name = models.CharField(max_length=200, default="")
    starred_course = models.ManyToManyField(Course, blank=True)

    def save(self, *args, **kwargs):
        if not self.preferred_name:
            self.preferred_name = self.user.first_name
        super().save(*args, **kwargs)

    def __str__(self):
        return self.user.first_name + " " + self.user.last_name

# Instructor (not including TAs)
class Instructor(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    teaching_course = models.ManyToManyField(Course)

    def __str__(self):
        return self.user.first_name + " " + self.user.last_name

class Queue(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    instructor = models.ManyToManyField(Instructor)
    question = models.CharField(max_length=500, default="")
    joined_time = models.DateTimeField(auto_now_add=True)
    ## if invited, not showing in instructor's waiting student queue,
    ## but showing in the serving queue
    invited = models.BooleanField(default=False)

    def __str__(self):
        return self.course.code + ": " + self.student.user.first_name \
            + " " + self.student.user.last_name

ohq/views.py
from django.db.models import constraints
from django.shortcuts import render
from django.http import HttpResponseRedirect, JsonResponse
from .models import Student, Instructor, Course, Queue
from django.contrib.auth.models import User, UserManager
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from django.views import generic
from django.contrib.auth import login, logout, authenticate
import re


# Create your views here.
class CourseListView(generic.ListView):
    model = Course
    template_name = "ohq/course_list.html"
    context_object_name = "course_list"

    def get_teaching_courses(self):
        is_instructor = Instructor.objects.filter(user=self.request.user).count()
        # at least teaching one courses
        if is_instructor:
            query = Instructor.objects.filter(user=self.request.user)\
                .all()[0].teaching_course.all()
            return query
        return Course.objects.none()
    
    def get_starred_courses(self):
        return Student.objects.filter(user=self.request.user).all()[0]\
            .starred_course.all()
        
    def render_to_response(self, context):
        if not self.request.user.id:
            return redirect('ohq:login')
        return super(CourseListView, self).render_to_response(context)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # preferred_courses are the courses being taught or starred by the user
        if not self.request.user.id:
            return context
        teaching_courses = self.get_teaching_courses()
        starred_courses = self.get_starred_courses()
        preferred_courses = teaching_courses.union(starred_courses)
        rest_courses = Course.objects.all().difference(preferred_courses)
        context["teaching_courses"] = teaching_courses
        context["starred_courses"] = starred_courses
        context["rest_courses"] = rest_courses
        # print(self.request.session.get_expiry_age())
        self.request.session.set_expiry(self.request.session.get_expiry_age())
        return context


class MyCourseListView(generic.ListView):
    model = Course
    template_name = "ohq/my_courses.html"
    context_object_name = "course_list"

    def get_teaching_courses(self):
        is_instructor = Instructor.objects.filter(user=self.request.user).count()
        # at least teaching one courses
        if is_instructor:
            query = Instructor.objects.filter(user=self.request.user)\
                .all()[0].teaching_course.all()
            return query
        return Instructor.objects.none()
    
    def get_starred_courses(self):
        return Student.objects.filter(user=self.request.user).all()[0]\
            .starred_course.all()

    def render_to_response(self, context):
        if not self.request.user.id:
            return redirect('ohq:login')
        return super(MyCourseListView, self).render_to_response(context)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # preferred_courses are the courses being taught or starred by the user
        if not self.request.user.id:
            return context
        teaching_courses = self.get_teaching_courses()
        starred_courses = self.get_starred_courses()
        context["teaching_courses"] = teaching_courses
        context["starred_courses"] = starred_courses
        self.request.session.set_expiry(self.request.session.get_expiry_age())
        return context

def prepare_search(request):
    request.session.set_expiry(request.session.get_expiry_age())
    if request.method == "POST":
        context = {}
        query = request.POST["search_query"]
        if not query or query.isspace():
            query = " "
        url = "search/q={}".format(query)
        return redirect(url)

    else:
        return render(request, "ohq/course_list.html")

def search(request, query):
    def get_teaching_courses():
        is_instructor = Instructor.objects.filter(user=request.user).count()
        # at least teaching one courses
        if is_instructor:
            query = Instructor.objects.filter(user=request.user)\
                .all()[0].teaching_course.all()
            return query
        return Instructor.objects.none()
    
    def get_starred_courses():
        return Student.objects.filter(user=request.user).all()[0]\
            .starred_course.all()

    request.session.set_expiry(request.session.get_expiry_age())
    if request.method == "GET":
        context = {}
        template = "ohq/search_result.html"

        context["search_query"] = query
        course_list = Course.objects.none()
        if query == " ":
            context["no_result"] = "You are searching for empty keywords. Here are all the courses."
            course_list = Course.objects.all()
        else:
            subject, number, _session = re.compile("([a-zA-Z]+)?([0-9]+)?([a-zA-Z]+)?").match(query).groups()
            if subject:
                course_list = Course.objects.filter(code__istartswith=query).all()
            else:
                if number:
                    course_list = Course.objects.filter(code__icontains=number).all()
            if len(course_list) == 0:
                context["no_result"] = "No results for {}, try another keywords".format(query)
        if len(course_list) == 0:
            course_list = Course.objects.filter(course_name__icontains=query).all()
        
        teaching_courses = get_teaching_courses()
        starred_courses = get_starred_courses()
        context["teaching_courses"] = teaching_courses.intersection(course_list)
        context["starred_courses"] = starred_courses.intersection(course_list)
        context["rest_courses"] = course_list.difference(teaching_courses, starred_courses)
        return render(request, template, context)

    else:
        return render(request, "ohq/course_list.html")


def check_is_instructor(user, course):
    is_instructor = False
    if user.id is not None:
        results = Instructor.objects.filter(user=user, teaching_course=course).count()
        if results > 0:
            is_instructor = True
    return is_instructor

def get_position_in_queue(user, course, joined_time):
    if user.id is not None:
        result = Queue.objects.filter(course=course, joined_time__lt=joined_time).count()
        return result
    return 0

def check_is_joined(user, course):
    if Queue.objects.filter(course=course, student=user.student).count() > 0:
        return True
    return False

def get_number_in_queue(course):
    return Queue.objects.filter(course=course).count()

class CourseQueueView(generic.DetailView):
    model = Course
    template_name = "ohq/course_queue.html"

    def render_to_response(self, context):
        if not self.request.user.id:
            return redirect('ohq:login')
        return super(CourseQueueView, self).render_to_response(context)

    def get_context_data(self, **kwargs):
        def get_queue(course):
            result = []
            query_set = Queue.objects.filter(course=course).order_by("joined_time").all()
            for q in query_set:
                temp = {}
                temp["first_name"] = q.student.user.first_name
                temp["question"] = q.question
                temp["queue_checkbox_id"] = q.student.user.username
                temp["invited"] = q.invited
                result.append(temp)
            return result

        def get_subqueue(course):
            result = []
            query_set = Queue.objects.filter(course=course, instructor=self.request.user.instructor).order_by("joined_time").all()
            if len(query_set) == 0:
                return result
            for q in query_set:
                temp = {}
                temp["first_name"] = q.student.user.first_name
                temp["question"] = q.question
                temp["queue_checkbox_id"] = q.student.user.username
                temp["invited"] = q.invited
                result.append(temp)
            return result

        context = super().get_context_data(**kwargs)
        if not self.request.user.id:
            return context
        course = get_object_or_404(Course, pk=self.kwargs["pk"])
        context["course_status"] = course.status
        is_instructor = check_is_instructor(self.request.user, course)
        if is_instructor:
            context["is_instructor"] = is_instructor
            context["queue"] = get_queue(course)
            context["sub_queue"] = get_subqueue(course)
        else:
            is_joined = check_is_joined(self.request.user, course)
            if not is_joined:
                context["is_joined"] = False
                context["number_in_queue"] = get_number_in_queue(course)
            else:
                # only 1 queue object per user allowed
                context["is_joined"] = True
                queue_obj = get_object_or_404(Queue, student=self.request.user.student)
                context["is_invited"] = queue_obj.invited
                joined_time = queue_obj.joined_time
                context["number_in_queue"] = get_position_in_queue(self.request.user, course, joined_time)
                context["student_question"] = queue_obj.question
                if queue_obj.invited:
                    context["link"] = course.meeting_link
        self.request.session.set_expiry(self.request.session.get_expiry_age())
        return context


def change_queue_status(request, pk):
    if not request.user.id:
        return redirect("ohq:login")
    request.session.set_expiry(request.session.get_expiry_age())
    if request.method == "POST":
        course = get_object_or_404(Course, pk=pk)
        is_instructor = check_is_instructor(request.user, course)
        if is_instructor:
            course.status = not course.status
            course.save()
    return redirect(request.META['HTTP_REFERER'])

ohq/templates/ohq/manage_account.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load static %}
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous">
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
      crossorigin="anonymous"></script>

    <meta charset="UTF-8">
    <title>OHQueue</title>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
      <div class="container-fluid">
        <a class="navbar-brand" href="/">OHQueue</a>
        <form action="{% url 'ohq:my_courses' %}">
          {% csrf_token %}
          <div class="btn-group" role="group">
            <button type="submit" class="btn btn-primary">My Courses</button>
            <button type="button" class="btn btn-primary">About</button>
          </div>
        </form>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
          data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent" aria-expanded="false"
          aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end"
          id="navbarSupportedContent">
          <form class="d-flex" action="{% url 'ohq:prepare_search' %}" method="post">
            {% csrf_token %}
            <input class="form-control me-2" type="search" 
            placeholder="Course e.g. CPEN502" aria-label="Search"
            name="search_query">
            <button class="btn btn-success" type="submit">Search</button>
          </form>
          {% if user.is_authenticated %}
          <ul class="navbar-nav mb-2 mb-lg-0">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown"
                role="button" data-bs-toggle="dropdown" aria-expanded="false">
                {{ user.student.preferred_name }}({{ user.username }})
              </a>
              <ul class="dropdown-menu dropdown-menu-end"
                aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item text-center" href="{% url 'ohq:change_password' %}">Manage Password</a></li>
                <li><a class="dropdown-item text-center" href="{% url 'ohq:logout' %}">Sign Out</a></li>
              </ul>
            </li>
          </ul>
          {% else %}
          <ul class="navbar-nav mb-2 mb-lg-0">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown"
                role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Sign In/Up
              </a>
              <ul class="dropdown-menu dropdown-menu-end"
                aria-labelledby="navbarDropdown">
                <li>
                  <form action="{% url 'ohq:login_request' %}" method="post"
                    accept-charset="UTF-8">
                    {% csrf_token %}
                    <input class="mx-3 mt-2" id="user_username" type="text"
                      name="user[username]" placeholder="Username">
                    <input class="mx-3 mt-2" id="user_password" type="password"
                      name="user[password]" placeholder="Password">
                    <div class="d-grid gap-2">
                      <button type="submit" class="mx-4 mt-2 btn btn-primary">
                        Sign In
                      </button>
                    </div>
                  </form>

                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item text-center" href="signup">Sign Up</a></li>
                  <li><a class="dropdown-item text-center" href="#">Forget Password?</a></li>
                </ul>
              </li>
            </ul>
            {% endif %}
          </div>
        </div>
      </nav>
      
      <div class="container mt-2">
        <h2>Manage Account</h2>
      </div>
      <div class="container">
        <!-- Form for change_preferred_name -->
        <form action="{% url 'ohq:change_preferred_name' %}" method="post">
          {% csrf_token %}
          <div class="container">
            <h3>Change Preferred Name</h3>
            <h4>Your current preferred name is: {{ user.student.preferred_name }}</h4>
            <div class="form-group">
              <label class="mt-2" for="new_preferred_name"><b>New Preferred Name</b></label>
              <input id="new_preferred_name" class="form-control" type="text"
                placeholder="Default is your first name" name="user[preferred_name]">
            </div>
            {% if name_message %}
            <div class="alert alert-warning mt-2"> <!--Style the message paragraph with .alert and .alert-warning class -->
              {{ name_message }}
            </div>
            {% endif %}
            {% if success_name_message %}
            <div class="alert alert-success mt-2"> <!--Style the message paragraph with .alert and .alert-warning class -->
              {{ success_name_message }}
            </div>
            {% endif %}
            <button class="btn btn-primary mt-2" type="submit">Change Preferred Name</button>
            <!--Style button with .btn and .btn-primary class -->
          </div>
        </form>
  
        <style type="text/css">
          .h-divider{
            margin-top:5px;
            margin-bottom:5px;
            height:1px;
            width:100%;
            border-top:2px solid gray;
          }
          </style>
        <div class="h-divider mt-2"></div>
  
        <form action="{% url 'ohq:change_password' %}" method="post">
          {% csrf_token %}
          <div class="container">
            <div class="form-group">
              <label class="mt-2" for="psw_old"><b>Old Password</b></label>
              <input id="psw_old" class="form-control" type="password"
                placeholder="Old Password" name="user[old_password]" required>
              <label class="mt-2" for="psw"><b>New Password</b></label>
              <input id="psw" class="form-control" type="password"
                placeholder="New Password" name="user[password]" required>
              <label class="mt-2" for="psw1"><b>Confirm Password</b></label>
              <input id="psw1" class="form-control" type="password"
                placeholder="Password Again" name="user[password1]" required>
            </div>
            {% if password_message %}
            <div class="alert alert-warning mt-2"> <!--Style the message paragraph with .alert and .alert-warning class -->
              {{ password_message }}
            </div>
            {% endif %}
            {% if success_password_message %}
            <div class="alert alert-success mt-2"> <!--Style the message paragraph with .alert and .alert-warning class -->
              {{ success_password_message }}
            </div>
            {% endif %}
            <button class="btn btn-primary mt-2" type="submit">Change Password</button>
            <!--Style button with .btn and .btn-primary class -->
          </div>
        </form>
      </div>
      

    </body>
  </html>

ohq/templates/ohq/my_courses.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load static %}
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous">
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
      crossorigin="anonymous"></script>

    <meta charset="UTF-8">
    <title>OHQueue</title>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
      <div class="container-fluid">
        <a class="navbar-brand" href="/">OHQueue</a>
        <form action="{% url 'ohq:my_courses' %}">
          {% csrf_token %}
          <div class="btn-group" role="group">
            <button type="submit" class="btn btn-primary">My Courses</button>
            <button type="button" class="btn btn-primary">About</button>
          </div>
        </form>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
          data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent" aria-expanded="false"
          aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end"
          id="navbarSupportedContent">
          <form class="d-flex" action="{% url 'ohq:prepare_search' %}" method="post">
            {% csrf_token %}
            <input class="form-control me-2" type="search" 
            placeholder="Course e.g. CPEN502" aria-label="Search"
            name="search_query">
            <button class="btn btn-success" type="submit">Search</button>
          </form>

          {% if user.is_authenticated %}
          <ul class="navbar-nav mb-2 mb-lg-0">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown"
                role="button" data-bs-toggle="dropdown" aria-expanded="false">
                {{ user.student.preferred_name }}({{ user.username }})
              </a>
              <ul class="dropdown-menu dropdown-menu-end"
                aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item text-center" href="{% url 'ohq:change_password' %}">Manage Account</a></li>
                <li><a class="dropdown-item text-center" href="{% url 'ohq:logout' %}">Sign Out</a></li>
              </ul>
            </li>
          </ul>
          {% else %}
          <ul class="navbar-nav mb-2 mb-lg-0">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown"
                role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Sign In/Up
              </a>
              <ul class="dropdown-menu dropdown-menu-end"
                aria-labelledby="navbarDropdown">
                <li>
                <form action="{% url 'ohq:login_request' %}" method="post"
                  accept-charset="UTF-8">
                  {% csrf_token %}
                  <input class="mx-3 mt-2" id="user_username" type="text"
                    name="user[username]" placeholder="Username">
                  <input class="mx-3 mt-2" id="user_password" type="password"
                    name="user[password]" placeholder="Password">
                  <div class="d-grid gap-2">
                    <button type="submit" class="mx-4 mt-2 btn btn-primary">
                      Sign In
                    </button>
                  </div>
                </form>
                </li> 
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item text-center" href="signup">Sign Up</a></li>
                <li><a class="dropdown-item text-center" href="#">Forget Password?</a></li>
              </ul>
            </li>
          </ul>
          {% endif %}
        </div>
      </div>
    </nav>

      <div class="container-fluid mt-2">
        {% if teaching_courses|length != 0 %}
        <h2>Courses I Teach</h2>
        {% endif %}
        <div class="card-columns-vertical">
          {% for course in teaching_courses %}
          <div class="card mt-2">
            <div class="card-header">
              <div class="row justify-content-between">
                <div class="col-11">
                  
                    <!-- show starred courses with a star or to star the course -->
                  <form action="/course/{{course.pk}}/star_course" method="post">
                    {% csrf_token %}
                    <h4>
                      <button type="submit" class="btn btn-sm btn-light" disabled>
                        <svg xmlns="http://www.w3.org/2000/svg" width="22"
                          height="22"
                          fill="currentColor" class="bi bi-star-fill" viewBox="0 0
                          16 16" style="fill:gold">
                          <path d="M3.612
                            15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173
                            6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927
                            0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522
                            3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389
                            2.256z"></path>
                        </svg>
                      </button>
                    {{ course.code }}: {{ course.course_name }} {{ course.pk }}
                    </h4>
                  </form>
                </div>
                <div class="col-1">
                  <input type=button class="btn btn-primary"
                    onClick="location.href='/course/{{ course.pk }}'"
                    value='Join'>
                </div>
              </div>
            </div>
            <div class="card-body">
              <p>
                {% if course.status %}
                Office hour is happening now!
                {% else %}
                Queue closed.
                {% endif %}
              </p>
            </div>
          </div>
          {% endfor %}

          <h2>Starred Courses</h2>
          {% for course in starred_courses %}
          <div class="card mt-2">
            <div class="card-header">
              <div class="row justify-content-between">
                <div class="col-11">
                  
                    <!-- show starred courses with a star or to star the course -->
                  <form action="/course/{{course.pk}}/star_course" method="post">
                    {% csrf_token %}
                    <h4>
                      <button type="submit" class="btn btn-sm btn-light">
                        <svg xmlns="http://www.w3.org/2000/svg" width="22"
                          height="22"
                          fill="currentColor" class="bi bi-star-fill" viewBox="0 0
                          16 16" style="fill:gold">
                          <path d="M3.612
                            15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173
                            6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927
                            0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522
                            3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389
                            2.256z"></path>
                        </svg>
                      </button>
                    {{ course.code }}: {{ course.course_name }} {{ course.pk }}
                    </h4>
                  </form>
                </div>
                <div class="col-1">
                  <input type=button class="btn btn-primary"
                    onClick="location.href='/course/{{ course.pk }}'"
                    value='Join'>
                </div>
              </div>
            </div>
            <div class="card-body">
              <p>
                {% if course.status %}
                Office hour is happening now!
                {% else %}
                Queue closed.
                {% endif %}
              </p>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>

    </body>
  </html>